AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Flask App on AWS App Runner using CloudFormation

Resources:
  FlaskAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: "apptest1"
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: "381492212823.dkr.ecr.us-east-2.amazonaws.com/xh/final01:latest" 
          ImageRepositoryType: ECR
        AutoDeploymentsEnabled: true
      InstanceConfiguration:
        Cpu: "1024" # 1 vCPU
        Memory: "2048" # 2 GB RAM
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: "/"
      NetworkConfiguration:
        EgressConfiguration:
          EgressType: DEFAULT

Outputs:
  AppRunnerServiceURL:
    Description: "URL of the deployed Flask app on App Runner"
    Value: !GetAtt FlaskAppRunnerService.ServiceUrl
